# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go get -v
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: athul
    name: shelby
brews:
  - name: shelby
    tap:
      owner: athul
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/athul/shelby"
    description: "A fast and minimal Shell Prompt in Go"
    install: bin.install "shelby"%
